export const ROUTES = {
  HOME: "/",
  PRODUCT: `/products`,
  CHECKOUT: "/checkout",
  CONTACT: "/contact-us",
  TERMS: "/terms",
  POLICY: "/privacy",
  FAQ: "/faq",
  FORGET_PASSWORD: "/forget-password",
  ACCOUNT: "/my-account",
  ORDERS: "/my-account/orders",
  ACCOUNT_DETAILS: "/my-account/account-details",
  CHANGE_PASSWORD: "/my-account/change-password",
  SHOPS: "/shops",
  LOGIN: "/signin",
  SIGN_UP: "/signup",
  SEARCH: "/search",
  COLLECTIONS: "/collections",
  CATEGORY: "/category",
  ORDER: "/order",
  DASHBOARD: "/dashboard",
  DASHBOARD_PRODUCT: "/dashboard/product",
  DASHBOARD_PRODUCTS: "/dashboard/products",
  DASHBOARD_VARIATION: "/dashboard/variation",
  DASHBOARD_CREATE_VARIANTS: "/dashboard/create-product-variants",
  DASHBOARD_CREATE_PRODUCT_STEPS: "/dashboard/create-product-steps",
};
